name: Mkdocs Build

on:
  push:
    branches: [ "v1", "v2" ]
  workflow_dispatch:   

jobs:
  mike-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install -r requirements/requirements.txt
        pip install mike==1.1.2
    - name: Config Git
      run: |
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
    - name: Build package
      run: |
        git fetch origin deploy:deploy
        mike deploy --push --branch deploy --rebase ${{ github.ref_name }}
        mike set-default -b deploy ${{ github.ref_name }}
