name: Deploy Docs to OSS

on:
  push:
    branches: [ "deploy" ]

  workflow_dispatch:

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ossutil
        run: |
          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
          
      - name: Deploy OSS
        env:
          ACCESS_KEY_ID: ${{ secrets.DATAEASE_OSS_AK }}
          ACCESS_KEY_SECRET: ${{ secrets.DATAEASE_OSS_SK }}
          ACCESS_KEY_BUCKET: ${{ secrets.DATAEASE_OSS_BUCKET }}
        run: |
          ossutil cp -r -f ./ oss://$ACCESS_KEY_BUCKET/docs --access-key-id=$ACCESS_KEY_ID --access-key-secret=$ACCESS_KEY_SECRET --endpoint=oss-cn-zhangjiakou.aliyuncs.com --exclude '.git*' 
