# This is a basic workflow to help you get started with Actions

name: Deploy Docs to Server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "deploy" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ssh-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: insert MaxKb code
        run: |
          sed -i '/<head>/a\
          <script>\
            window.maxkbChatConfig = {\
            token: "5baa787163381fa2",\
            host: "maxkb.fit2cloud.com",\
            protocol:"https:"\
          }\
          </script>\
          <script src="https://maxkb.fit2cloud.com/ui/embeb.js">\
          </script>
          ' v1/index.html

          sed -i '/<head>/a\
          <script>\
            window.maxkbChatConfig = {\
            token: "2ddd8b594ce09dbb",\
            host: "maxkb.fit2cloud.com",\
            protocol:"https:"\
          }\
          </script>\
          <script src="https://maxkb.fit2cloud.com/ui/embeb.js">\
          </script>
          ' v2/index.html
      
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: dataease.io
          REMOTE_USER: root
          SOURCE: ./
          TARGET: /opt/dataease/docs
          # Arguments to pass to rsync
          ARGS: "-rltgoDzvO --delete"
          # An array of folder to exclude
          EXCLUDE: ".git/"
